### ISSUE TITLE
Lista de elementos que faltam na pág.Inscrever-se

### ISSUE THREAD

**Issue by suriiipingu** [suriiipingu/prjSpacebarWebsiteTCC#3]
**MAIS IMPORTANTES**
- Imagem do lado do formulário (parte de design);
- Adicionar novos países; (feito)
- Arrumar o footer; 
- Arrumar o head;

**MENOS IMPORTANTES**
- Validar todos os campos;

**Comment by IgorTeodoro** [comment]
feitos todos os pontos
